-- AlterTable
ALTER TABLE `bookings` MODIFY `status` ENUM('PENDING_CONFIRM', 'APPROVED', 'AWAITING_PAYMENT', 'PAID', 'REJECTED', 'CANCELLED', 'COMPLETED', 'PAY_FAILED', 'CHECKED_IN', 'PAYMENT_EXPIRED', 'NO_SHOW') NULL DEFAULT 'PENDING_CONFIRM';
