import type { Field, Review } from "@/types"

export interface FieldDetails extends Field {
  description: string
  amenities: string[]
  capacity: number
  owner: {
    name: string
    phone: string
    email: string
    rating: number
    reviews: number
  }
}

export interface User {
  id: number
  name: string
  email: string
  phone: string
  avatar?: string
  role: "user" | "owner" | "admin"
  createdAt: string
  status: "active" | "inactive" | "banned"
  totalBookings: number
}

export interface AdminUser extends User {
  lastLogin: string
  registeredFields: number
}

export interface Booking {
  id: number
  fieldId: number
  fieldName: string
  ownerId: number
  userId: number
  userName: string
  date: string
  startTime: string
  endTime: string
  status: "pending" | "confirmed" | "cancelled" | "completed"
  totalPrice: number
  createdAt: string
  notes?: string
}

export interface Voucher {
  id: number
  code: string
  ownerId: number
  description: string
  discountType: "percentage" | "fixed"
  discountValue: number
  maxUses: number
  usedCount: number
  validFrom: string
  validTo: string
  minBookingAmount: number
  active: boolean
}

export interface FieldApproval {
  id: number
  fieldId: number
  fieldName: string
  ownerId: number
  ownerName: string
  status: "pending" | "approved" | "rejected"
  submittedAt: string
  reviewedAt?: string
  rejectionReason?: string
}

export const MOCK_FIELDS: Field[] = [
  {
    id: 1,
    name: "Sân Bóng Đá Green Valley",
    type: "Bóng đá",
    rating: 4.8,
    reviews: 124,
    location: "123 Lê Lợi, Quận 1, TP.HCM",
    district: "Quận 1",
    price: 500000,
    image: "/soccer-field-green-grass.jpg",
    openTime: "06:00",
    closeTime: "22:00",
    available: true,
  },
  {
    id: 2,
    name: "Sân Cầu Lông Pro",
    type: "Cầu lông",
    rating: 4.6,
    reviews: 89,
    location: "45 Võ Văn Tần, Quận 3, TP.HCM",
    district: "Quận 3",
    price: 200000,
    image: "/indoor-badminton-court.png",
    openTime: "07:00",
    closeTime: "21:00",
    available: true,
  },
  {
    id: 3,
    name: "Sân Bóng Rổ Arena",
    type: "Bóng rổ",
    rating: 4.9,
    reviews: 156,
    location: "789 Nguyễn Hữu Thọ, Quận 7, TP.HCM",
    district: "Quận 7",
    price: 400000,
    image: "/indoor-basketball-court.png",
    openTime: "08:00",
    closeTime: "22:00",
    available: true,
  },
  {
    id: 4,
    name: "Sân Tennis Elite",
    type: "Tennis",
    rating: 4.7,
    reviews: 102,
    location: "567 Mai Chí Thọ, Quận 2, TP.HCM",
    district: "Quận 2",
    price: 350000,
    image: "/professional-tennis-court.jpg",
    openTime: "06:00",
    closeTime: "20:00",
    available: false,
  },
  {
    id: 5,
    name: "Sân Bóng Chuyền Sunset",
    type: "Bóng chuyền",
    rating: 4.5,
    reviews: 78,
    location: "234 Hoàng Diệu, Quận 4, TP.HCM",
    district: "Quận 4",
    price: 250000,
    image: "/beach-volleyball-court.png",
    openTime: "06:00",
    closeTime: "21:00",
    available: true,
  },
  {
    id: 6,
    name: "Sân Bóng Đá Mini Star",
    type: "Bóng đá",
    rating: 4.4,
    reviews: 67,
    location: "100 Điện Biên Phủ, Bình Thạnh, TP.HCM",
    district: "Bình Thạnh",
    price: 450000,
    image: "/mini-football-field-night.jpg",
    openTime: "07:00",
    closeTime: "23:00",
    available: true,
  },
  {
    id: 7,
    name: "Sân Pickleball Sunrise",
    type: "Pickleball",
    rating: 4.7,
    reviews: 45,
    location: "88 Nguyễn Văn Linh, Quận 7, TP.HCM",
    district: "Quận 7",
    price: 180000,
    image: "/pickleball-court.jpg",
    openTime: "06:00",
    closeTime: "21:00",
    available: true,
  },
  {
    id: 8,
    name: "Sân Bóng Đá Victory",
    type: "Bóng đá",
    rating: 4.6,
    reviews: 98,
    location: "200 Cách Mạng Tháng 8, Quận 10, TP.HCM",
    district: "Quận 10",
    price: 480000,
    image: "/soccer-field-green-grass.jpg",
    openTime: "06:00",
    closeTime: "22:00",
    available: true,
  },
  {
    id: 9,
    name: "Sân Cầu Lông Olympic",
    type: "Cầu lông",
    rating: 4.8,
    reviews: 134,
    location: "55 Trần Hưng Đạo, Quận 5, TP.HCM",
    district: "Quận 5",
    price: 220000,
    image: "/indoor-badminton-court.png",
    openTime: "07:00",
    closeTime: "22:00",
    available: true,
  },
  {
    id: 10,
    name: "Sân Tennis Champion",
    type: "Tennis",
    rating: 4.5,
    reviews: 76,
    location: "321 Lý Thường Kiệt, Tân Bình, TP.HCM",
    district: "Tân Bình",
    price: 320000,
    image: "/professional-tennis-court.jpg",
    openTime: "06:00",
    closeTime: "20:00",
    available: true,
  },
  {
    id: 11,
    name: "Sân Bóng Rổ Slam Dunk",
    type: "Bóng rổ",
    rating: 4.7,
    reviews: 112,
    location: "456 Phan Xích Long, Phú Nhuận, TP.HCM",
    district: "Phú Nhuận",
    price: 380000,
    image: "/indoor-basketball-court.png",
    openTime: "08:00",
    closeTime: "22:00",
    available: true,
  },
  {
    id: 12,
    name: "Sân Bóng Chuyền Beach",
    type: "Bóng chuyền",
    rating: 4.3,
    reviews: 54,
    location: "789 Nguyễn Thị Minh Khai, Quận 3, TP.HCM",
    district: "Quận 3",
    price: 230000,
    image: "/beach-volleyball-court.png",
    openTime: "06:00",
    closeTime: "21:00",
    available: false,
  },
  {
    id: 13,
    name: "Sân Bóng Đá Galaxy",
    type: "Bóng đá",
    rating: 4.9,
    reviews: 187,
    location: "111 Nguyễn Huệ, Quận 1, TP.HCM",
    district: "Quận 1",
    price: 550000,
    image: "/mini-football-field-night.jpg",
    openTime: "06:00",
    closeTime: "23:00",
    available: true,
  },
  {
    id: 14,
    name: "Sân Cầu Lông Vũ Cầu",
    type: "Cầu lông",
    rating: 4.4,
    reviews: 67,
    location: "234 Hai Bà Trưng, Quận 1, TP.HCM",
    district: "Quận 1",
    price: 190000,
    image: "/indoor-badminton-court.png",
    openTime: "07:00",
    closeTime: "21:00",
    available: true,
  },
  {
    id: 15,
    name: "Sân Tennis Grand Slam",
    type: "Tennis",
    rating: 4.8,
    reviews: 143,
    location: "567 Điện Biên Phủ, Quận 3, TP.HCM",
    district: "Quận 3",
    price: 400000,
    image: "/professional-tennis-court.jpg",
    openTime: "06:00",
    closeTime: "20:00",
    available: true,
  },
  {
    id: 16,
    name: "Sân Pickleball Central",
    type: "Pickleball",
    rating: 4.6,
    reviews: 38,
    location: "123 Lê Văn Sỹ, Quận 3, TP.HCM",
    district: "Quận 3",
    price: 170000,
    image: "/pickleball-court.jpg",
    openTime: "06:00",
    closeTime: "21:00",
    available: true,
  },
  {
    id: 17,
    name: "Sân Bóng Rổ All Star",
    type: "Bóng rổ",
    rating: 4.5,
    reviews: 89,
    location: "890 Võ Văn Kiệt, Quận 5, TP.HCM",
    district: "Quận 5",
    price: 350000,
    image: "/indoor-basketball-court.png",
    openTime: "08:00",
    closeTime: "22:00",
    available: true,
  },
  {
    id: 18,
    name: "Sân Bóng Đá Dream Field",
    type: "Bóng đá",
    rating: 4.7,
    reviews: 156,
    location: "456 Lê Đại Hành, Quận 11, TP.HCM",
    district: "Quận 11",
    price: 420000,
    image: "/soccer-field-green-grass.jpg",
    openTime: "06:00",
    closeTime: "22:00",
    available: true,
  },
  {
    id: 19,
    name: "Sân Cầu Lông Feather",
    type: "Cầu lông",
    rating: 4.3,
    reviews: 52,
    location: "789 Nguyễn Đình Chiểu, Quận 3, TP.HCM",
    district: "Quận 3",
    price: 180000,
    image: "/indoor-badminton-court.png",
    openTime: "07:00",
    closeTime: "21:00",
    available: true,
  },
  {
    id: 20,
    name: "Sân Bóng Chuyền Sky High",
    type: "Bóng chuyền",
    rating: 4.6,
    reviews: 71,
    location: "321 Pasteur, Quận 1, TP.HCM",
    district: "Quận 1",
    price: 280000,
    image: "/beach-volleyball-court.png",
    openTime: "06:00",
    closeTime: "21:00",
    available: true,
  },
  {
    id: 21,
    name: "Sân Tennis Ace",
    type: "Tennis",
    rating: 4.4,
    reviews: 63,
    location: "654 Nguyễn Trãi, Quận 5, TP.HCM",
    district: "Quận 5",
    price: 340000,
    image: "/professional-tennis-court.jpg",
    openTime: "06:00",
    closeTime: "20:00",
    available: false,
  },
  {
    id: 22,
    name: "Sân Bóng Đá United",
    type: "Bóng đá",
    rating: 4.8,
    reviews: 198,
    location: "987 Hoàng Văn Thụ, Tân Bình, TP.HCM",
    district: "Tân Bình",
    price: 520000,
    image: "/mini-football-field-night.jpg",
    openTime: "06:00",
    closeTime: "23:00",
    available: true,
  },
  {
    id: 23,
    name: "Sân Pickleball Fun Zone",
    type: "Pickleball",
    rating: 4.5,
    reviews: 42,
    location: "246 Trường Chinh, Tân Bình, TP.HCM",
    district: "Tân Bình",
    price: 160000,
    image: "/pickleball-court.jpg",
    openTime: "06:00",
    closeTime: "21:00",
    available: true,
  },
  {
    id: 24,
    name: "Sân Bóng Rổ Pro Court",
    type: "Bóng rổ",
    rating: 4.9,
    reviews: 167,
    location: "135 Nguyễn Văn Trỗi, Phú Nhuận, TP.HCM",
    district: "Phú Nhuận",
    price: 450000,
    image: "/indoor-basketball-court.png",
    openTime: "08:00",
    closeTime: "22:00",
    available: true,
  },
]

export const MOCK_FIELD_DETAILS: Record<number, FieldDetails> = {
  1: {
    id: 1,
    name: "Sân Bóng Đá Green Valley",
    type: "Bóng đá",
    rating: 4.8,
    reviews: 124,
    location: "123 Lê Lợi, Quận 1, TP.HCM",
    district: "Quận 1",
    price: 500000,
    image: "/soccer-field-green-grass.jpg",
    openTime: "06:00",
    closeTime: "22:00",
    available: true,
    description:
      "Sân bóng đá chuyên nghiệp với cỏ nhân tạo cao cấp, phù hợp cho thi đấu và tập luyện. Trang bị đầy đủ tiện nghi hiện đại bao gồm phòng thay đồ, bãi đỗ xe và khu vực khán giả.",
    amenities: ["Bãi đỗ xe", "Phòng thay đồ", "Phòng tắm", "Khu khán giả", "Đèn chiếu sáng", "Cho thuê dụng cụ"],
    capacity: 22,
    owner: {
      name: "Green Valley Sports",
      phone: "0123 456 789",
      email: "contact@greenvalley.com",
      rating: 4.8,
      reviews: 156,
    },
  },
  2: {
    id: 2,
    name: "Sân Cầu Lông Pro",
    type: "Cầu lông",
    rating: 4.6,
    reviews: 89,
    location: "45 Võ Văn Tần, Quận 3, TP.HCM",
    district: "Quận 3",
    price: 200000,
    image: "/indoor-badminton-court.png",
    openTime: "07:00",
    closeTime: "21:00",
    available: true,
    description: "Sân cầu lông trong nhà với hệ thống chiếu sáng chuyên nghiệp, sàn gỗ cao cấp và điều hòa mát mẻ.",
    amenities: ["Điều hòa", "Phòng thay đồ", "Cho thuê vợt", "Nước uống miễn phí", "WiFi"],
    capacity: 4,
    owner: {
      name: "Pro Badminton Center",
      phone: "0987 654 321",
      email: "info@probadminton.vn",
      rating: 4.6,
      reviews: 89,
    },
  },
  3: {
    id: 3,
    name: "Sân Bóng Rổ Arena",
    type: "Bóng rổ",
    rating: 4.9,
    reviews: 156,
    location: "789 Nguyễn Hữu Thọ, Quận 7, TP.HCM",
    district: "Quận 7",
    price: 400000,
    image: "/indoor-basketball-court.png",
    openTime: "08:00",
    closeTime: "22:00",
    available: true,
    description:
      "Sân bóng rổ tiêu chuẩn NBA với sàn gỗ chuyên dụng, bảng rổ điều chỉnh được và hệ thống điểm số điện tử.",
    amenities: ["Sàn gỗ chuyên dụng", "Bảng điểm điện tử", "Phòng thay đồ", "Bãi đỗ xe", "Máy lạnh"],
    capacity: 10,
    owner: {
      name: "Arena Sports Complex",
      phone: "0909 888 777",
      email: "booking@arena.vn",
      rating: 4.9,
      reviews: 156,
    },
  },
  4: {
    id: 4,
    name: "Sân Tennis Elite",
    type: "Tennis",
    rating: 4.7,
    reviews: 102,
    location: "567 Mai Chí Thọ, Quận 2, TP.HCM",
    district: "Quận 2",
    price: 350000,
    image: "/professional-tennis-court.jpg",
    openTime: "06:00",
    closeTime: "20:00",
    available: false,
    description: "Sân tennis mặt cứng tiêu chuẩn quốc tế, phù hợp cho cả tập luyện và thi đấu chuyên nghiệp.",
    amenities: ["Mặt sân cứng", "Đèn chiếu sáng", "Cho thuê vợt", "Huấn luyện viên", "Cafeteria"],
    capacity: 4,
    owner: {
      name: "Elite Tennis Club",
      phone: "0912 345 678",
      email: "info@elitetennis.vn",
      rating: 4.7,
      reviews: 102,
    },
  },
  5: {
    id: 5,
    name: "Sân Bóng Chuyền Sunset",
    type: "Bóng chuyền",
    rating: 4.5,
    reviews: 78,
    location: "234 Hoàng Diệu, Quận 4, TP.HCM",
    district: "Quận 4",
    price: 250000,
    image: "/beach-volleyball-court.png",
    openTime: "06:00",
    closeTime: "21:00",
    available: true,
    description: "Sân bóng chuyền bãi biển với cát trắng mịn, view sông tuyệt đẹp và không gian thoáng mát.",
    amenities: ["Cát trắng", "Phòng tắm", "Ghế nghỉ", "Quầy nước", "Đèn chiếu sáng"],
    capacity: 12,
    owner: {
      name: "Sunset Beach Sports",
      phone: "0933 222 111",
      email: "hello@sunsetbeach.vn",
      rating: 4.5,
      reviews: 78,
    },
  },
  6: {
    id: 6,
    name: "Sân Bóng Đá Mini Star",
    type: "Bóng đá",
    rating: 4.4,
    reviews: 67,
    location: "100 Điện Biên Phủ, Bình Thạnh, TP.HCM",
    district: "Bình Thạnh",
    price: 450000,
    image: "/mini-football-field-night.jpg",
    openTime: "07:00",
    closeTime: "23:00",
    available: true,
    description: "Sân bóng đá mini 5 người với cỏ nhân tạo thế hệ mới, hệ thống đèn LED hiện đại cho trận đấu đêm.",
    amenities: ["Cỏ nhân tạo", "Đèn LED", "Phòng thay đồ", "Căng tin", "Bãi xe miễn phí"],
    capacity: 10,
    owner: {
      name: "Star Football Club",
      phone: "0944 555 666",
      email: "dat@starfc.vn",
      rating: 4.4,
      reviews: 67,
    },
  },
  7: {
    id: 7,
    name: "Sân Pickleball Sunrise",
    type: "Pickleball",
    rating: 4.7,
    reviews: 45,
    location: "88 Nguyễn Văn Linh, Quận 7, TP.HCM",
    district: "Quận 7",
    price: 180000,
    image: "/pickleball-court.jpg",
    openTime: "06:00",
    closeTime: "21:00",
    available: true,
    description: "Sân pickleball với không gian thoáng mát và tiện nghi đầy đủ.",
    amenities: ["Bãi đỗ xe", "Phòng thay đồ", "Phòng tắm", "Đèn chiếu sáng", "Cho thuê vợt"],
    capacity: 6,
    owner: {
      name: "Sunrise Pickleball Club",
      phone: "0977 666 555",
      email: "contact@sunrisepickleball.vn",
      rating: 4.7,
      reviews: 45,
    },
  },
  8: {
    id: 8,
    name: "Sân Bóng Đá Victory",
    type: "Bóng đá",
    rating: 4.6,
    reviews: 98,
    location: "200 Cách Mạng Tháng 8, Quận 10, TP.HCM",
    district: "Quận 10",
    price: 480000,
    image: "/soccer-field-green-grass.jpg",
    openTime: "06:00",
    closeTime: "22:00",
    available: true,
    description: "Sân bóng đá Victory với cỏ nhân tạo cao cấp và không gian rộng rãi.",
    amenities: ["Cỏ nhân tạo", "Bãi đỗ xe", "Phòng thay đồ", "Khu vực khán giả", "Đèn chiếu sáng"],
    capacity: 20,
    owner: {
      name: "Victory Sports",
      phone: "0966 555 444",
      email: "contact@victorysports.vn",
      rating: 4.6,
      reviews: 98,
    },
  },
  9: {
    id: 9,
    name: "Sân Cầu Lông Olympic",
    type: "Cầu lông",
    rating: 4.8,
    reviews: 134,
    location: "55 Trần Hưng Đạo, Quận 5, TP.HCM",
    district: "Quận 5",
    price: 220000,
    image: "/indoor-badminton-court.png",
    openTime: "07:00",
    closeTime: "22:00",
    available: true,
    description: "Sân cầu lông Olympic với hệ thống chiếu sáng chuyên nghiệp và không gian thoáng mát.",
    amenities: ["Điều hòa", "Phòng thay đồ", "Cho thuê vợt", "Nước uống miễn phí", "WiFi"],
    capacity: 4,
    owner: {
      name: "Olympic Badminton Center",
      phone: "0955 444 333",
      email: "info@olympicbadminton.vn",
      rating: 4.8,
      reviews: 134,
    },
  },
  10: {
    id: 10,
    name: "Sân Tennis Champion",
    type: "Tennis",
    rating: 4.5,
    reviews: 76,
    location: "321 Lý Thường Kiệt, Tân Bình, TP.HCM",
    district: "Tân Bình",
    price: 320000,
    image: "/professional-tennis-court.jpg",
    openTime: "06:00",
    closeTime: "20:00",
    available: true,
    description: "Sân tennis Champion với mặt sân cứng tiêu chuẩn quốc tế và đầy đủ tiện nghi.",
    amenities: ["Mặt sân cứng", "Đèn chiếu sáng", "Cho thuê vợt", "Huấn luyện viên", "Cafeteria"],
    capacity: 4,
    owner: {
      name: "Champion Tennis Club",
      phone: "0944 333 222",
      email: "info@championtennis.vn",
      rating: 4.5,
      reviews: 76,
    },
  },
  11: {
    id: 11,
    name: "Sân Bóng Rổ Slam Dunk",
    type: "Bóng rổ",
    rating: 4.7,
    reviews: 112,
    location: "456 Phan Xích Long, Phú Nhuận, TP.HCM",
    district: "Phú Nhuận",
    price: 380000,
    image: "/indoor-basketball-court.png",
    openTime: "08:00",
    closeTime: "22:00",
    available: true,
    description: "Sân bóng rổ Slam Dunk với không gian rộng rãi và hệ thống điểm số điện tử.",
    amenities: ["Sàn gỗ chuyên dụng", "Bảng điểm điện tử", "Phòng thay đồ", "Bãi đỗ xe", "Máy lạnh"],
    capacity: 10,
    owner: {
      name: "Slam Dunk Sports Complex",
      phone: "0933 222 111",
      email: "booking@slamdunk.vn",
      rating: 4.7,
      reviews: 112,
    },
  },
  12: {
    id: 12,
    name: "Sân Bóng Chuyền Beach",
    type: "Bóng chuyền",
    rating: 4.3,
    reviews: 54,
    location: "789 Nguyễn Thị Minh Khai, Quận 3, TP.HCM",
    district: "Quận 3",
    price: 230000,
    image: "/beach-volleyball-court.png",
    openTime: "06:00",
    closeTime: "21:00",
    available: false,
    description: "Sân bóng chuyền bãi biển với cát trắng mịn và không gian thoáng mát.",
    amenities: ["Cát trắng", "Phòng tắm", "Ghế nghỉ", "Quầy nước", "Đèn chiếu sáng"],
    capacity: 12,
    owner: {
      name: "Beach Volleyball Club",
      phone: "0922 111 000",
      email: "contact@beachvolleyball.vn",
      rating: 4.3,
      reviews: 54,
    },
  },
  13: {
    id: 13,
    name: "Sân Bóng Đá Galaxy",
    type: "Bóng đá",
    rating: 4.9,
    reviews: 187,
    location: "111 Nguyễn Huệ, Quận 1, TP.HCM",
    district: "Quận 1",
    price: 550000,
    image: "/mini-football-field-night.jpg",
    openTime: "06:00",
    closeTime: "23:00",
    available: true,
    description: "Sân bóng đá Galaxy với cỏ nhân tạo thế hệ mới và hệ thống đèn LED hiện đại.",
    amenities: ["Cỏ nhân tạo", "Đèn LED", "Phòng thay đồ", "Căng tin", "Bãi xe miễn phí"],
    capacity: 10,
    owner: {
      name: "Galaxy Football Club",
      phone: "0911 000 999",
      email: "dat@galaxyfc.vn",
      rating: 4.9,
      reviews: 187,
    },
  },
  14: {
    id: 14,
    name: "Sân Cầu Lông Vũ Cầu",
    type: "Cầu lông",
    rating: 4.4,
    reviews: 67,
    location: "234 Hai Bà Trưng, Quận 1, TP.HCM",
    district: "Quận 1",
    price: 190000,
    image: "/indoor-badminton-court.png",
    openTime: "07:00",
    closeTime: "21:00",
    available: true,
    description: "Sân cầu lông Vũ Cầu với hệ thống chiếu sáng chuyên nghiệp và không gian rộng rãi.",
    amenities: ["Điều hòa", "Phòng thay đồ", "Cho thuê vợt", "Nước uống miễn phí", "WiFi"],
    capacity: 4,
    owner: {
      name: "Vũ Cầu Badminton Center",
      phone: "0900 999 888",
      email: "info@vucaubadminton.vn",
      rating: 4.4,
      reviews: 67,
    },
  },
  15: {
    id: 15,
    name: "Sân Tennis Grand Slam",
    type: "Tennis",
    rating: 4.8,
    reviews: 143,
    location: "567 Điện Biên Phủ, Quận 3, TP.HCM",
    district: "Quận 3",
    price: 400000,
    image: "/professional-tennis-court.jpg",
    openTime: "06:00",
    closeTime: "20:00",
    available: true,
    description: "Sân tennis Grand Slam với mặt sân cứng tiêu chuẩn quốc tế và đầy đủ tiện nghi.",
    amenities: ["Mặt sân cứng", "Đèn chiếu sáng", "Cho thuê vợt", "Huấn luyện viên", "Cafeteria"],
    capacity: 4,
    owner: {
      name: "Grand Slam Tennis Club",
      phone: "0999 888 777",
      email: "info@grandslamtennis.vn",
      rating: 4.8,
      reviews: 143,
    },
  },
  16: {
    id: 16,
    name: "Sân Pickleball Central",
    type: "Pickleball",
    rating: 4.6,
    reviews: 38,
    location: "123 Lê Văn Sỹ, Quận 3, TP.HCM",
    district: "Quận 3",
    price: 170000,
    image: "/pickleball-court.jpg",
    openTime: "06:00",
    closeTime: "21:00",
    available: true,
    description: "Sân pickleball Central với không gian thoáng mát và tiện nghi đầy đủ.",
    amenities: ["Bãi đỗ xe", "Phòng thay đồ", "Phòng tắm", "Đèn chiếu sáng", "Cho thuê vợt"],
    capacity: 6,
    owner: {
      name: "Central Pickleball Club",
      phone: "0988 777 666",
      email: "contact@centralpickleball.vn",
      rating: 4.6,
      reviews: 38,
    },
  },
  17: {
    id: 17,
    name: "Sân Bóng Rổ All Star",
    type: "Bóng rổ",
    rating: 4.5,
    reviews: 89,
    location: "890 Võ Văn Kiệt, Quận 5, TP.HCM",
    district: "Quận 5",
    price: 350000,
    image: "/indoor-basketball-court.png",
    openTime: "08:00",
    closeTime: "22:00",
    available: true,
    description: "Sân bóng rổ All Star với không gian rộng rãi và hệ thống điểm số điện tử.",
    amenities: ["Sàn gỗ chuyên dụng", "Bảng điểm điện tử", "Phòng thay đồ", "Bãi đỗ xe", "Máy lạnh"],
    capacity: 10,
    owner: {
      name: "All Star Sports Complex",
      phone: "0977 666 555",
      email: "booking@allstar.vn",
      rating: 4.5,
      reviews: 89,
    },
  },
  18: {
    id: 18,
    name: "Sân Bóng Đá Dream Field",
    type: "Bóng đá",
    rating: 4.7,
    reviews: 156,
    location: "456 Lê Đại Hành, Quận 11, TP.HCM",
    district: "Quận 11",
    price: 420000,
    image: "/soccer-field-green-grass.jpg",
    openTime: "06:00",
    closeTime: "22:00",
    available: true,
    description: "Sân bóng đá Dream Field với cỏ nhân tạo cao cấp và không gian rộng rãi.",
    amenities: ["Cỏ nhân tạo", "Bãi đỗ xe", "Phòng thay đồ", "Khu vực khán giả", "Đèn chiếu sáng"],
    capacity: 20,
    owner: {
      name: "Dream Field Sports",
      phone: "0966 555 444",
      email: "contact@dreamfield.vn",
      rating: 4.7,
      reviews: 156,
    },
  },
  19: {
    id: 19,
    name: "Sân Cầu Lông Feather",
    type: "Cầu lông",
    rating: 4.3,
    reviews: 52,
    location: "789 Nguyễn Đình Chiểu, Quận 3, TP.HCM",
    district: "Quận 3",
    price: 180000,
    image: "/indoor-badminton-court.png",
    openTime: "07:00",
    closeTime: "21:00",
    available: true,
    description: "Sân cầu lông Feather với hệ thống chiếu sáng chuyên nghiệp và không gian rộng rãi.",
    amenities: ["Điều hòa", "Phòng thay đồ", "Cho thuê vợt", "Nước uống miễn phí", "WiFi"],
    capacity: 4,
    owner: {
      name: "Feather Badminton Center",
      phone: "0955 444 333",
      email: "info@featherbadminton.vn",
      rating: 4.3,
      reviews: 52,
    },
  },
  20: {
    id: 20,
    name: "Sân Bóng Chuyền Sky High",
    type: "Bóng chuyền",
    rating: 4.6,
    reviews: 71,
    location: "321 Pasteur, Quận 1, TP.HCM",
    district: "Quận 1",
    price: 280000,
    image: "/beach-volleyball-court.png",
    openTime: "06:00",
    closeTime: "21:00",
    available: true,
    description: "Sân bóng chuyền Sky High với cát trắng mịn và không gian thoáng mát.",
    amenities: ["Cát trắng", "Phòng tắm", "Ghế nghỉ", "Quầy nước", "Đèn chiếu sáng"],
    capacity: 12,
    owner: {
      name: "Sky High Volleyball Club",
      phone: "0944 333 222",
      email: "contact@skyhighvolleyball.vn",
      rating: 4.6,
      reviews: 71,
    },
  },
  21: {
    id: 21,
    name: "Sân Tennis Ace",
    type: "Tennis",
    rating: 4.4,
    reviews: 63,
    location: "654 Nguyễn Trãi, Quận 5, TP.HCM",
    district: "Quận 5",
    price: 340000,
    image: "/professional-tennis-court.jpg",
    openTime: "06:00",
    closeTime: "20:00",
    available: false,
    description: "Sân tennis Ace với mặt sân cứng tiêu chuẩn quốc tế và đầy đủ tiện nghi.",
    amenities: ["Mặt sân cứng", "Đèn chiếu sáng", "Cho thuê vợt", "Huấn luyện viên", "Cafeteria"],
    capacity: 4,
    owner: {
      name: "Ace Tennis Club",
      phone: "0933 222 111",
      email: "info@acetennis.vn",
      rating: 4.4,
      reviews: 63,
    },
  },
  22: {
    id: 22,
    name: "Sân Bóng Đá United",
    type: "Bóng đá",
    rating: 4.8,
    reviews: 198,
    location: "987 Hoàng Văn Thụ, Tân Bình, TP.HCM",
    district: "Tân Bình",
    price: 520000,
    image: "/mini-football-field-night.jpg",
    openTime: "06:00",
    closeTime: "23:00",
    available: true,
    description: "Sân bóng đá United với cỏ nhân tạo thế hệ mới và hệ thống đèn LED hiện đại.",
    amenities: ["Cỏ nhân tạo", "Đèn LED", "Phòng thay đồ", "Căng tin", "Bãi xe miễn phí"],
    capacity: 10,
    owner: {
      name: "United Football Club",
      phone: "0922 111 000",
      email: "dat@unitedfc.vn",
      rating: 4.8,
      reviews: 198,
    },
  },
  23: {
    id: 23,
    name: "Sân Pickleball Fun Zone",
    type: "Pickleball",
    rating: 4.5,
    reviews: 42,
    location: "246 Trường Chinh, Tân Bình, TP.HCM",
    district: "Tân Bình",
    price: 160000,
    image: "/pickleball-court.jpg",
    openTime: "06:00",
    closeTime: "21:00",
    available: true,
    description: "Sân pickleball Fun Zone với không gian thoáng mát và tiện nghi đầy đủ.",
    amenities: ["Bãi đỗ xe", "Phòng thay đồ", "Phòng tắm", "Đèn chiếu sáng", "Cho thuê vợt"],
    capacity: 6,
    owner: {
      name: "Fun Zone Pickleball Club",
      phone: "0911 000 999",
      email: "contact@funzonepickleball.vn",
      rating: 4.5,
      reviews: 42,
    },
  },
  24: {
    id: 24,
    name: "Sân Bóng Rổ Pro Court",
    type: "Bóng rổ",
    rating: 4.9,
    reviews: 167,
    location: "135 Nguyễn Văn Trỗi, Phú Nhuận, TP.HCM",
    district: "Phú Nhuận",
    price: 450000,
    image: "/indoor-basketball-court.png",
    openTime: "08:00",
    closeTime: "22:00",
    available: true,
    description: "Sân bóng rổ Pro Court với không gian rộng rãi và hệ thống điểm số điện tử.",
    amenities: ["Sàn gỗ chuyên dụng", "Bảng điểm điện tử", "Phòng thay đồ", "Bãi đỗ xe", "Máy lạnh"],
    capacity: 10,
    owner: {
      name: "Pro Court Sports Complex",
      phone: "0900 999 888",
      email: "booking@procourt.vn",
      rating: 4.9,
      reviews: 167,
    },
  },
}

export const MOCK_USERS: User[] = [
  {
    id: 1,
    name: "Nguyễn Văn A",
    email: "nguyenvana@example.com",
    phone: "0901234567",
    avatar: "/male-avatar.jpg",
    role: "user",
    createdAt: "2024-01-15",
    status: "active",
    totalBookings: 12,
  },
  {
    id: 2,
    name: "Trần Thị B",
    email: "tranthib@example.com",
    phone: "0912345678",
    avatar: "/female-avatar.jpg",
    role: "user",
    createdAt: "2024-01-20",
    status: "active",
    totalBookings: 8,
  },
  {
    id: 3,
    name: "Lê Minh C",
    email: "leminc@example.com",
    phone: "0923456789",
    role: "user",
    createdAt: "2024-02-10",
    status: "active",
    totalBookings: 5,
  },
  {
    id: 4,
    name: "Phạm Hồng D",
    email: "phamhongd@example.com",
    phone: "0934567890",
    role: "user",
    createdAt: "2024-02-15",
    status: "inactive",
    totalBookings: 2,
  },
  {
    id: 5,
    name: "Trần Văn B",
    email: "tranvanb@example.com",
    phone: "0945678901",
    avatar: "/male-avatar.jpg",
    role: "owner",
    createdAt: "2024-01-10",
    status: "active",
    totalBookings: 150,
  },
  {
    id: 6,
    name: "Nguyễn Thị C",
    email: "nguyenthic@example.com",
    phone: "0956789012",
    role: "owner",
    createdAt: "2024-01-25",
    status: "active",
    totalBookings: 89,
  },
]

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 1,
    fieldId: 1,
    fieldName: "Sân Bóng Đá Green Valley",
    ownerId: 5,
    userId: 1,
    userName: "Nguyễn Văn A",
    date: "2024-12-20",
    startTime: "18:00",
    endTime: "19:00",
    status: "confirmed",
    totalPrice: 500000,
    createdAt: "2024-12-15",
    notes: "Sân nhân dân",
  },
  {
    id: 2,
    fieldId: 2,
    fieldName: "Sân Cầu Lông Pro",
    ownerId: 6,
    userId: 2,
    userName: "Trần Thị B",
    date: "2024-12-21",
    startTime: "19:00",
    endTime: "20:00",
    status: "pending",
    totalPrice: 200000,
    createdAt: "2024-12-16",
  },
  {
    id: 3,
    fieldId: 3,
    fieldName: "Sân Bóng Rổ Arena",
    ownerId: 5,
    userId: 1,
    userName: "Nguyễn Văn A",
    date: "2024-12-22",
    startTime: "20:00",
    endTime: "21:00",
    status: "confirmed",
    totalPrice: 400000,
    createdAt: "2024-12-10",
  },
  {
    id: 4,
    fieldId: 1,
    fieldName: "Sân Bóng Đá Green Valley",
    ownerId: 5,
    userId: 3,
    userName: "Lê Minh C",
    date: "2024-12-19",
    startTime: "17:00",
    endTime: "18:00",
    status: "completed",
    totalPrice: 500000,
    createdAt: "2024-12-10",
  },
  {
    id: 5,
    fieldId: 2,
    fieldName: "Sân Cầu Lông Pro",
    ownerId: 6,
    userId: 4,
    userName: "Phạm Hồng D",
    date: "2024-12-18",
    startTime: "18:00",
    endTime: "19:00",
    status: "cancelled",
    totalPrice: 200000,
    createdAt: "2024-12-08",
  },
]

export const MOCK_VOUCHERS: Voucher[] = [
  {
    id: 1,
    code: "SAVE10",
    ownerId: 5,
    description: "Giảm 10% cho tất cả đơn đặt sân",
    discountType: "percentage",
    discountValue: 10,
    maxUses: 100,
    usedCount: 45,
    validFrom: "2024-12-01",
    validTo: "2024-12-31",
    minBookingAmount: 200000,
    active: true,
  },
  {
    id: 2,
    code: "FLAT50K",
    ownerId: 5,
    description: "Giảm 50K cho đơn hàng trên 500K",
    discountType: "fixed",
    discountValue: 50000,
    maxUses: 50,
    usedCount: 28,
    validFrom: "2024-12-01",
    validTo: "2024-12-31",
    minBookingAmount: 500000,
    active: true,
  },
  {
    id: 3,
    code: "WELCOME20",
    ownerId: 6,
    description: "Giảm 20% cho khách hàng mới",
    discountType: "percentage",
    discountValue: 20,
    maxUses: 200,
    usedCount: 87,
    validFrom: "2024-11-01",
    validTo: "2024-12-31",
    minBookingAmount: 100000,
    active: true,
  },
  {
    id: 4,
    code: "EXPIRED20",
    ownerId: 5,
    description: "Khuyến mãi Tết (hết hạn)",
    discountType: "percentage",
    discountValue: 20,
    maxUses: 300,
    usedCount: 250,
    validFrom: "2024-01-01",
    validTo: "2024-02-29",
    minBookingAmount: 300000,
    active: false,
  },
]

export const MOCK_FIELD_APPROVALS: FieldApproval[] = [
  {
    id: 1,
    fieldId: 7,
    fieldName: "Sân Pickleball Vàng Anh",
    ownerId: 7,
    ownerName: "Vũ Tuấn Anh",
    status: "pending",
    submittedAt: "2024-12-10",
  },
  {
    id: 2,
    fieldId: 8,
    fieldName: "Sân Squash Legend",
    ownerId: 8,
    ownerName: "Hoàng Kiến Thành",
    status: "pending",
    submittedAt: "2024-12-12",
  },
  {
    id: 3,
    fieldId: 9,
    fieldName: "Sân Gym Star Fitness",
    ownerId: 9,
    ownerName: "Đặng Quốc Vũ",
    status: "rejected",
    submittedAt: "2024-12-05",
    reviewedAt: "2024-12-08",
    rejectionReason: "Giấy phép kinh doanh không rõ ràng",
  },
  {
    id: 4,
    fieldId: 10,
    fieldName: "Sân Bóng Chuyền Xanh",
    ownerId: 10,
    ownerName: "Lê Thị Hồng Hạnh",
    status: "approved",
    submittedAt: "2024-11-20",
    reviewedAt: "2024-12-01",
  },
]

export const MOCK_REVIEWS: Review[] = [
  {
    id: 1,
    userId: 1,
    userName: "Nguyễn Văn A",
    fieldId: 1,
    rating: 5,
    comment: "Sân rất đẹp, sạch sẽ và tiện nghi đầy đủ. Nhân viên thân thiện!",
    date: "2 ngày trước",
  },
  {
    id: 2,
    userId: 2,
    userName: "Trần Thị B",
    fieldId: 1,
    rating: 4,
    comment: "Giá cả hợp lý, vị trí thuận tiện. Sẽ quay lại lần sau.",
    date: "1 tuần trước",
  },
  {
    id: 3,
    userId: 3,
    userName: "Lê Minh C",
    fieldId: 2,
    rating: 5,
    comment: "Hệ thống đặt sân online rất tiện lợi. Recommend!",
    date: "2 tuần trước",
  },
]

export function getFieldById(id: number): Field | undefined {
  return MOCK_FIELDS.find((field) => field.id === id)
}

export function getFieldDetailsById(id: number): FieldDetails | undefined {
  return MOCK_FIELD_DETAILS[id]
}

export function getReviewsByFieldId(fieldId: number): Review[] {
  return MOCK_REVIEWS.filter((review) => review.fieldId === fieldId)
}

export function getAdminUsers(): AdminUser[] {
  return MOCK_USERS.map((user) => ({
    ...user,
    lastLogin: "2024-12-16T10:30:00Z",
    registeredFields: user.role === "owner" ? Math.floor(Math.random() * 5) + 1 : 0,
  }))
}

export function getBookingsByStatus(status: string): Booking[] {
  return MOCK_BOOKINGS.filter((booking) => booking.status === status)
}

export function getVouchersByOwner(ownerId: number): Voucher[] {
  return MOCK_VOUCHERS.filter((voucher) => voucher.ownerId === ownerId)
}

export function getFieldApprovalsStatus(status: string): FieldApproval[] {
  return MOCK_FIELD_APPROVALS.filter((approval) => approval.status === status)
}

export function getUserById(id: number): User | undefined {
  return MOCK_USERS.find((user) => user.id === id)
}

export function getBookingById(id: number): Booking | undefined {
  return MOCK_BOOKINGS.find((booking) => booking.id === id)
}
