-- AlterTable
ALTER TABLE `bookings` ADD COLUMN `checked_in_at` DATETIME(0) NULL,
    ADD COLUMN `checked_in_by` INTEGER NULL,
    ADD COLUMN `checkin_method` VARCHAR(20) NULL,
    MODIFY `status` ENUM('PENDING_CONFIRM', 'APPROVED', 'AWAITING_PAYMENT', 'PAID', 'REJECTED', 'CANCELLED', 'COMPLETED', 'PAY_FAILED', 'CHECKED_IN') NULL DEFAULT 'PENDING_CONFIRM';
