-- AlterTable
ALTER TABLE `bookings` ADD COLUMN `payment_expires_at` DATETIME(0) NULL,
    MODIFY `status` ENUM('PENDING_CONFIRM', 'APPROVED', 'AWAITING_PAYMENT', 'PAID', 'REJECTED', 'CANCELLED', 'COMPLETED', 'PAY_FAILED', 'CHECKED_IN', 'PAYMENT_EXPIRED') NULL DEFAULT 'PENDING_CONFIRM';
